### PR TITLE
Added a count badge to the RSVP Table

### PR DESCRIPTION
**Pull request by ATechAdventurer**
How the proposed change looks: [https://imgur.com/a/urO9B](https://imgur.com/a/urO9B)

### CODE REVIEW

**Comment by denzuko** [comment]
Those checks do not seem related but please include a few [webdriver based phpunit tests](https://cakebaker.wordpress.com/2006/03/22/selenium/) for the change.

Also, what if  ```count($event->registrations``` is null, zero, or empty? What kind of user experience should one expect?

**Comment by ATechAdventurer** [comment]
in cases of null, zero and empty count will return 0 making the badge say that no one has RSVP'd. I have added 2 checks to make sure that the evaluated object is never not set or empty, doing so will make it display 0, implying that no one has RSVP'd or there is some internal error.

**Comment by denzuko** [comment]
Code looks good, we just need the webdriver test and then this will be accepted into the build pipeline.

**Comment by clone1018** [comment]
@denzuko We have no testing infrastructure at all in the Calendar, with no existing tests and zero example webdriver tests. This is unnecessary.

**Comment by ATechAdventurer** [comment]
@clone1018 @denzuko I don’t have a local calendar setup, so I have no guarantee it works. If it gets merged please test it locally first.

**Comment by clone1018** [comment]
The only real feedback I have is count would also show cancelled registrations. Is that the intent? Might be confusing for users.

**Comment by ATechAdventurer** [comment]
You are completely right, I wasn’t to sure what that object contained, I assumed it was only for positive RSVPs

**Comment by clone1018** [comment]
Here's an example of a class would show:

image

It might be interesting to have two of the badges, one for Confirmed and one for Cancelled?

**Comment by ATechAdventurer** [comment]
I know that `$event->registrations` Is an array of registration objects. What is the value that determines the state of the RSVP in a Registration object?

**Comment by denzuko** [comment]
@clone1018 @manosteele91827 A correction, we *do* have testing infrastructure in place, that's the travis-ci reporting failings on other unit tests and we'll address the technical debt there as we go but mainly want to eliminate new technical debt on that front.

While our cicd and testing is a big part of going forward with several initiatives as it makes it easier on all of us as volunteers to maintain these systems but lets not make that the focus of this thread. 

Now, I do agree with @clone1018 that a case for cancelled or confirmed badge could be added and that maybe a counter badge for attended could round out the UI/UX.

**Comment by denzuko** [comment]
@manosteele91827 I would believe that's somewhere's in the Entity/Events.php model. I'll look around to get a better answer

**Comment by ATechAdventurer** [comment]
I’ll keep looking around

**Comment by clone1018** [comment]
I have a copy of the calender running on my laptop if you want to test some night at DMS. I'll respond later with a dump of $event->registrations

**Comment by denzuko** [comment]
https://github.com/Dallas-Makerspace/calendar/blob/master/src/Model/Table/RegistrationsTable.php#L94-L98

its the `Pending` value for status

**Comment by ATechAdventurer** [comment]
Is there a docker container for the calendar?

**Comment by clone1018** [comment]
No, even if you get the calendar running, authentication is only done via LDAP. I've been slowly making progress on a "DMS Testing OpenLDAP" docker container. With AD schema and some of our builtin stuff preloaded

**Comment by denzuko** [comment]
@manosteele91827 All of our current docker images are up on the hub: https://hub.docker.com/r/dallasmakerspace/ but as of right now this doesn't get built into one for production, another technical debt we're addressing, but there should be definitions in the internal gitlab on the VCC Community Grid.

**Comment by denzuko** [comment]
Ok gents, docker image is at https://hub.docker.com/r/dallasmakerspace/calendar

**Comment by denzuko** [comment]
Merging UI changes with the caveat that in an upcoming sprint we halt _all_ new features for dedication to code coverage and bug squashing. I'll even bring the pizza and age appropriate drinks for that hack-a-thon.

**Pull request merged**
